package seokhoon.trade.adapter.persistence;
import jakarta.persistence.*;import seokhoon.trade.domain.research.*;import java.math.BigDecimal;import java.time.*;
@Entity @Table(name="earnings_consensus_snapshots",uniqueConstraints=@UniqueConstraint(name="uk_earnings_consensus",columnNames={"stock_code","fiscal_year","fiscal_quarter","consensus_date","source"}))
public class EarningsConsensusSnapshotEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id;@Column(name="stock_code",nullable=false,length=20)String stockCode;@Column(name="fiscal_year",nullable=false)int fiscalYear;@Column(name="fiscal_quarter",nullable=false)int fiscalQuarter;@Column(name="consensus_date",nullable=false)LocalDate consensusDate;
 @Column(name="expected_revenue",precision=19,scale=4)BigDecimal expectedRevenue;@Column(name="expected_operating_income",precision=19,scale=4)BigDecimal expectedOperatingIncome;@Column(name="expected_net_income",precision=19,scale=4)BigDecimal expectedNetIncome;@Column(name="expected_operating_margin",precision=19,scale=4)BigDecimal expectedOperatingMargin;@Column(name="analyst_count")Integer analystCount;
 @Enumerated(EnumType.STRING)@Column(name="source",nullable=false,length=20)ConsensusSource source;@Column(name="provider_name",length=100)String providerName;@Enumerated(EnumType.STRING)@Column(name="status",nullable=false,length=20)ConsensusStatus status;@Column(name="created_at",nullable=false)Instant createdAt;@Column(name="updated_at",nullable=false)Instant updatedAt;protected EarningsConsensusSnapshotEntity(){}
 static EarningsConsensusSnapshotEntity from(EarningsConsensusSnapshot v){var e=new EarningsConsensusSnapshotEntity();e.id=v.id();e.update(v);return e;}void update(EarningsConsensusSnapshot v){stockCode=v.stockCode();fiscalYear=v.fiscalYear();fiscalQuarter=v.fiscalQuarter();consensusDate=v.consensusDate();expectedRevenue=v.expectedRevenue();expectedOperatingIncome=v.expectedOperatingIncome();expectedNetIncome=v.expectedNetIncome();expectedOperatingMargin=v.expectedOperatingMargin();analystCount=v.analystCount();source=v.source();providerName=v.providerName();status=v.status();createdAt=v.createdAt();updatedAt=v.updatedAt();}
 EarningsConsensusSnapshot toDomain(){return new EarningsConsensusSnapshot(id,stockCode,fiscalYear,fiscalQuarter,consensusDate,expectedRevenue,expectedOperatingIncome,expectedNetIncome,expectedOperatingMargin,analystCount,source,providerName,status,createdAt,updatedAt);}
}
