package seokhoon.trade.application.service;
import org.junit.jupiter.api.Test;import seokhoon.trade.application.port.in.ConsensusUseCase.*;import seokhoon.trade.application.port.out.*;import seokhoon.trade.config.ConsensusProviderProperties;import seokhoon.trade.domain.research.*;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.assertThat;
class ConsensusServiceTest {
 static final Instant NOW=Instant.parse("2026-06-15T00:00:00Z");
 @Test void importsEarningsAndTargetCsvAndFindsLatest(){var e=new EarningsMemory();var t=new TargetMemory();var service=service(e,t);
  var earnings=service.importEarningsCsv(("stockCode,fiscalYear,fiscalQuarter,consensusDate,expectedRevenue,expectedOperatingIncome,expectedNetIncome,expectedOperatingMargin,analystCount,source,providerName\n005930,2026,2,2026-06-14,1000,150,100,15,12,CSV,licensed-source").getBytes());
  var targets=service.importTargetPriceCsv(("stockCode,consensusDate,targetPrice,currentPrice,upsideRate,analystCount,source,providerName\n005930,2026-06-14,90000,75000,,10,CSV,licensed-source").getBytes());
  assertThat(earnings).singleElement().extracting(EarningsConsensusSnapshot::expectedRevenue).isEqualTo(new java.math.BigDecimal("1000"));assertThat(targets).singleElement().extracting(TargetPriceConsensusSnapshot::upsideRate).isEqualTo(new java.math.BigDecimal("20.0000"));assertThat(e.findLatest("005930",2026,2)).isPresent();}
 @Test void manualSaveMarksOldConsensusStale(){var service=service(new EarningsMemory(),new TargetMemory());var value=service.saveEarnings(new EarningsConsensusCommand("005930",2025,4,LocalDate.of(2025,1,1),null,null,null,null,null,ConsensusSource.MANUAL,null));assertThat(value.status()).isEqualTo(ConsensusStatus.STALE);}
 private static ConsensusService service(EarningsMemory e,TargetMemory t){return new ConsensusService(e,t,new ConsensusProviderProperties(),OperationalMetricsPort.noop(),Clock.fixed(NOW,ZoneOffset.UTC));}
 static class EarningsMemory implements EarningsConsensusPort{List<EarningsConsensusSnapshot>v=new ArrayList<>();public EarningsConsensusSnapshot save(EarningsConsensusSnapshot x){v.add(x);return x;}public List<EarningsConsensusSnapshot>find(String c,Integer y,Integer q){return v.stream().filter(x->x.stockCode().equals(c)).filter(x->y==null||x.fiscalYear()==y).filter(x->q==null||x.fiscalQuarter()==q).sorted(Comparator.comparing(EarningsConsensusSnapshot::consensusDate).reversed()).toList();}public Optional<EarningsConsensusSnapshot>findLatest(String c,int y,int q){return find(c,y,q).stream().findFirst();}public List<EarningsConsensusSnapshot>findAllEarnings(){return v;}}
 static class TargetMemory implements TargetPriceConsensusPort{List<TargetPriceConsensusSnapshot>v=new ArrayList<>();public TargetPriceConsensusSnapshot save(TargetPriceConsensusSnapshot x){v.add(x);return x;}public List<TargetPriceConsensusSnapshot>findByStockCode(String c){return v.stream().filter(x->x.stockCode().equals(c)).toList();}public Optional<TargetPriceConsensusSnapshot>findLatest(String c){return findByStockCode(c).stream().max(Comparator.comparing(TargetPriceConsensusSnapshot::consensusDate));}public List<TargetPriceConsensusSnapshot>findAllTargetPrices(){return v;}}
}
