package seokhoon.trade.application.service;

import org.junit.jupiter.api.Test;
import seokhoon.trade.application.port.in.*;
import seokhoon.trade.application.port.out.*;
import seokhoon.trade.config.InvestorFlowProperties;
import seokhoon.trade.domain.market.KisInvestorFlowAmountUnit;
import seokhoon.trade.domain.scheduler.*;
import java.time.*;
import java.util.Arrays;
import java.util.List;
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;

class InvestorFlowSchedulersTest {
    @Test void importSchedulerSkipsNonTradingDayWithoutProviderUseCase(){var useCase=mock(ImportInvestorFlowsUseCase.class);var calendar=mock(MarketCalendarPort.class);when(calendar.isTradingDay(any())).thenReturn(false);var history=new History();var properties=new InvestorFlowProperties();properties.setImportAutoRun(true);var scheduler=new InvestorFlowImportScheduler(useCase,calendar,history,OperationalMetricsPort.noop(),ids(),properties,clock());scheduler.importFlows();assertThat(history.status).isEqualTo(SchedulerExecutionStatus.SKIPPED);assertThat(history.reason).isEqualTo("NON_TRADING_DAY");verifyNoInteractions(useCase);}
    @Test void importSchedulerSkipsWhenProviderDisabled(){var useCase=mock(ImportInvestorFlowsUseCase.class);var calendar=mock(MarketCalendarPort.class);when(calendar.isTradingDay(any())).thenReturn(true);when(calendar.previousTradingDay(any())).thenReturn(LocalDate.of(2026,6,12));var history=new History();var properties=new InvestorFlowProperties();properties.setImportAutoRun(true);var scheduler=new InvestorFlowImportScheduler(useCase,calendar,history,OperationalMetricsPort.noop(),ids(),properties,clock());scheduler.importFlows();assertThat(history.status).isEqualTo(SchedulerExecutionStatus.SKIPPED);assertThat(history.reason).isEqualTo("PROVIDER_DISABLED");verifyNoInteractions(useCase);}
    @Test void importSchedulerCallsWatchlistOnlyWhenProviderAndAutoRunAreEnabled(){var useCase=mock(ImportInvestorFlowsUseCase.class);var calendar=mock(MarketCalendarPort.class);when(calendar.isTradingDay(any())).thenReturn(true);var previous=LocalDate.of(2026,6,12);when(calendar.previousTradingDay(any())).thenReturn(previous);when(useCase.importWatchlist(previous)).thenReturn(List.of());var history=new History();var properties=new InvestorFlowProperties();properties.setImportAutoRun(true);properties.setProviderEnabled(true);properties.setKisAmountUnit(KisInvestorFlowAmountUnit.KRW);var scheduler=new InvestorFlowImportScheduler(useCase,calendar,history,OperationalMetricsPort.noop(),ids(),properties,clock());scheduler.importFlows();verify(useCase).importWatchlist(previous);assertThat(history.status).isEqualTo(SchedulerExecutionStatus.SUCCEEDED);}
    @Test void importSchedulerSkipsUnverifiedUnitWithoutCallingImportOrDiagnostic(){var useCase=mock(ImportInvestorFlowsUseCase.class);var calendar=mock(MarketCalendarPort.class);when(calendar.isTradingDay(any())).thenReturn(true);when(calendar.previousTradingDay(any())).thenReturn(LocalDate.of(2026,6,12));var history=new History();var properties=new InvestorFlowProperties();properties.setImportAutoRun(true);properties.setProviderEnabled(true);properties.setDiagnosticEnabled(true);properties.setDiagnosticAllowHttp(true);var scheduler=new InvestorFlowImportScheduler(useCase,calendar,history,OperationalMetricsPort.noop(),ids(),properties,clock());scheduler.importFlows();assertThat(history.status).isEqualTo(SchedulerExecutionStatus.SKIPPED);assertThat(history.reason).isEqualTo("AMOUNT_UNIT_UNVERIFIED");verifyNoInteractions(useCase);assertThat(Arrays.stream(InvestorFlowImportScheduler.class.getDeclaredConstructors()).flatMap(v->Arrays.stream(v.getParameterTypes())).map(Class::getName)).noneMatch(v->v.contains("Diagnostic"));}
    @Test void analysisSchedulerSkipsNonTradingDay(){var useCase=mock(AnalyzeSupplyDemandUseCase.class);var calendar=mock(MarketCalendarPort.class);when(calendar.isTradingDay(any())).thenReturn(false);var history=new History();var scheduler=new SupplyDemandAnalysisScheduler(useCase,calendar,history,OperationalMetricsPort.noop(),ids(),new InvestorFlowProperties(),clock());scheduler.analyze();assertThat(history.status).isEqualTo(SchedulerExecutionStatus.SKIPPED);verifyNoInteractions(useCase);}
    @Test void analysisSchedulerSkipsUnverifiedUnitWithoutAnalysisOrDiagnostic(){var useCase=mock(AnalyzeSupplyDemandUseCase.class);var calendar=mock(MarketCalendarPort.class);when(calendar.isTradingDay(any())).thenReturn(true);when(calendar.previousTradingDay(any())).thenReturn(LocalDate.of(2026,6,12));var history=new History();var properties=new InvestorFlowProperties();properties.setProviderEnabled(true);properties.setDiagnosticEnabled(true);properties.setDiagnosticAllowHttp(true);var scheduler=new SupplyDemandAnalysisScheduler(useCase,calendar,history,OperationalMetricsPort.noop(),ids(),properties,clock());scheduler.analyze();assertThat(history.status).isEqualTo(SchedulerExecutionStatus.SKIPPED);assertThat(history.reason).isEqualTo("AMOUNT_UNIT_UNVERIFIED");verifyNoInteractions(useCase);assertThat(Arrays.stream(SupplyDemandAnalysisScheduler.class.getDeclaredConstructors()).flatMap(v->Arrays.stream(v.getParameterTypes())).map(Class::getName)).noneMatch(v->v.contains("Diagnostic"));}
    private static Clock clock(){return Clock.fixed(Instant.parse("2026-06-14T00:00:00Z"),ZoneId.of("Asia/Seoul"));}
    private static CorrelationIdProvider ids(){return new CorrelationIdProvider(){public String currentCorrelationId(){return "corr";}public String newCorrelationId(){return "corr";}};}
    private static class History implements SchedulerExecutionHistoryPort{SchedulerExecutionStatus status;String reason;public long saveStarted(SchedulerName n,LocalDate d,String c,Instant a){status=SchedulerExecutionStatus.STARTED;return 1;}public void markSucceeded(long id,int c,int s,boolean sent,Instant a){status=SchedulerExecutionStatus.SUCCEEDED;}public void markFailed(long id,String r,Instant a){status=SchedulerExecutionStatus.FAILED;reason=r;}public void markSkipped(SchedulerName n,LocalDate d,String r,String c,Instant a){status=SchedulerExecutionStatus.SKIPPED;reason=r;}public List<SchedulerExecutionHistoryRecord> find(LocalDate d,SchedulerName n,SchedulerExecutionStatus s){return List.of();}}
}
