package seokhoon.trade.application.service;
import org.junit.jupiter.api.Test; import seokhoon.trade.application.port.out.*; import seokhoon.trade.config.NaverNewsProperties;
import seokhoon.trade.domain.research.*; import seokhoon.trade.domain.stock.*; import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.assertThat; import static org.mockito.Mockito.*;
class NewsImportServiceTest {
 @Test void disabledProviderSkipsWithoutExternalCall(){NewsProviderPort provider=mock(NewsProviderPort.class);var repo=new MemoryNews();var props=new NaverNewsProperties();var service=service(provider,repo,props);var result=service.importQuery("삼성전자",20);assertThat(result.status()).isEqualTo(NewsImportStatus.SKIPPED);assertThat(repo.histories.getFirst().failureReason()).isEqualTo("NEWS_PROVIDER_DISABLED");verifyNoInteractions(provider);}
 @Test void missingCredentialsFailsWithoutLeakingSecrets(){NewsProviderPort provider=mock(NewsProviderPort.class);var repo=new MemoryNews();var props=new NaverNewsProperties();props.setProviderEnabled(true);var result=service(provider,repo,props).importQuery("삼성전자",20);assertThat(result.status()).isEqualTo(NewsImportStatus.FAILED);assertThat(result.reason()).isEqualTo("NAVER_NEWS_CREDENTIALS_MISSING");verifyNoInteractions(provider);}
 @Test void savesMetadataMentionClassificationAndDeduplicates(){NewsProviderPort provider=mock(NewsProviderPort.class);when(provider.search("삼성전자",20)).thenReturn(List.of(new NewsProviderPort.ProviderNews("대규모 <b>공급계약</b>","수주 계약",null,"https://news.naver.com/a", "example.com",Instant.parse("2026-06-22T00:00:00Z"))));var repo=new MemoryNews();var props=enabled();StockPort stocks=mock(StockPort.class);when(stocks.findByStockCode("005930")).thenReturn(Optional.of(new Stock("005930","삼성전자",Market.KOSPI,true)));var service=new NewsImportService(provider,repo,stocks,props,new NewsClassificationService(),OperationalMetricsPort.noop(),Clock.fixed(Instant.parse("2026-06-22T01:00:00Z"),ZoneOffset.UTC));var first=service.importStock("005930");var second=service.importStock("005930");assertThat(first.savedCount()).isEqualTo(1);assertThat(second.duplicatedCount()).isEqualTo(1);assertThat(repo.articles).hasSize(1);assertThat(repo.articles.getFirst().category()).isEqualTo(NewsCategory.ORDER_CONTRACT);assertThat(repo.mentions).singleElement().satisfies(v->assertThat(v.stockCode()).isEqualTo("005930"));assertThat(repo.articles.getFirst().summary()).doesNotContain("본문");}
 private static NewsImportService service(NewsProviderPort p,MemoryNews r,NaverNewsProperties props){return new NewsImportService(p,r,mock(StockPort.class),props,new NewsClassificationService(),OperationalMetricsPort.noop(),Clock.fixed(Instant.parse("2026-06-22T01:00:00Z"),ZoneOffset.UTC));}
 private static NaverNewsProperties enabled(){var p=new NaverNewsProperties();p.setProviderEnabled(true);p.setClientId("id");p.setClientSecret("secret");return p;}
 static class MemoryNews implements NewsRepositoryPort {final List<NewsArticle>articles=new ArrayList<>();final List<NewsStockMention>mentions=new ArrayList<>();final List<NewsImportHistory>histories=new ArrayList<>();long seq;
 public Optional<NewsArticle>findBySourceHash(String h){return articles.stream().filter(v->v.sourceHash().equals(h)).findFirst();}public Optional<NewsArticle>findByNormalizedTitleHash(String h){return articles.stream().filter(v->v.normalizedTitleHash().equals(h)).findFirst();}public NewsArticle saveArticle(NewsArticle v){var x=new NewsArticle(++seq,v.provider(),v.title(),v.summary(),v.originLink(),v.link(),v.publisher(),v.publishedAt(),v.collectedAt(),v.query(),v.normalizedTitleHash(),v.sourceHash(),v.category(),v.sentiment(),v.importance(),v.shortReason(),v.createdAt(),v.updatedAt());articles.add(x);return x;}public void saveMention(NewsStockMention v){if(mentions.stream().noneMatch(x->x.newsArticleId().equals(v.newsArticleId())&&x.stockCode().equals(v.stockCode())))mentions.add(v);}public NewsImportHistory saveHistory(NewsImportHistory v){histories.add(v);return v;}public List<NewsArticle>findArticles(String c,Instant f,Instant t){return articles;}public List<NewsImportHistory>findHistories(String q,int l){return histories;}public long countCollectedBetween(Instant f,Instant t){return articles.size();}public long countByImportanceBetween(NewsImportance i,Instant f,Instant t){return articles.stream().filter(v->v.importance()==i).count();}public long countRiskBetween(Instant f,Instant t){return 0;}}
}
