package seokhoon.trade.application.service;
import org.springframework.beans.factory.annotation.Autowired;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import seokhoon.trade.application.port.in.ConsensusUseCase;import seokhoon.trade.application.port.out.*;import seokhoon.trade.config.ConsensusProviderProperties;import seokhoon.trade.domain.research.*;import java.math.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;
@Service public class ConsensusService implements ConsensusUseCase {
 private final EarningsConsensusPort earnings;private final TargetPriceConsensusPort targets;private final ConsensusProviderProperties properties;private final OperationalMetricsPort metrics;private final Clock clock;
 @Autowired public ConsensusService(EarningsConsensusPort earnings,TargetPriceConsensusPort targets,ConsensusProviderProperties properties,OperationalMetricsPort metrics){this(earnings,targets,properties,metrics,Clock.systemUTC());}
 ConsensusService(EarningsConsensusPort earnings,TargetPriceConsensusPort targets,ConsensusProviderProperties properties,OperationalMetricsPort metrics,Clock clock){this.earnings=earnings;this.targets=targets;this.properties=properties;this.metrics=metrics;this.clock=clock;}
 @Transactional public EarningsConsensusSnapshot saveEarnings(EarningsConsensusCommand c){Instant now=clock.instant();ConsensusStatus status=status(c.consensusDate());var saved=earnings.save(new EarningsConsensusSnapshot(null,c.stockCode(),c.fiscalYear(),c.fiscalQuarter(),c.consensusDate(),c.expectedRevenue(),c.expectedOperatingIncome(),c.expectedNetIncome(),c.expectedOperatingMargin(),c.analystCount(),c.source()==null?ConsensusSource.MANUAL:c.source(),clean(c.providerName()),status,now,now));metrics.recordConsensusSnapshot("earnings",status==ConsensusStatus.STALE?"stale":"saved");return saved;}
 @Transactional public TargetPriceConsensusSnapshot saveTargetPrice(TargetPriceConsensusCommand c){Instant now=clock.instant();BigDecimal upside=c.upsideRate()!=null?c.upsideRate():upside(c.targetPrice(),c.currentPrice());ConsensusStatus status=status(c.consensusDate());var saved=targets.save(new TargetPriceConsensusSnapshot(null,c.stockCode(),c.consensusDate(),c.targetPrice(),c.currentPrice(),upside,c.analystCount(),c.source()==null?ConsensusSource.MANUAL:c.source(),clean(c.providerName()),status,now,now));metrics.recordConsensusSnapshot("target_price",status==ConsensusStatus.STALE?"stale":"saved");return saved;}
 public List<EarningsConsensusSnapshot> importEarningsCsv(byte[] csv){try{List<String[]>rows=rows(csv);List<EarningsConsensusSnapshot>out=new ArrayList<>();for(String[]v:rows)out.add(saveEarnings(new EarningsConsensusCommand(v[0],integer(v[1]),integer(v[2]),date(v[3]),decimal(v[4]),decimal(v[5]),decimal(v[6]),decimal(v[7]),nullableInt(v[8]),source(v[9]),nullable(v[10]))));metrics.recordConsensusImport("earnings","success");return out;}catch(RuntimeException e){metrics.recordConsensusImport("earnings","failure");throw new IllegalArgumentException("invalid earnings consensus CSV",e);}}
 public List<TargetPriceConsensusSnapshot> importTargetPriceCsv(byte[] csv){try{List<String[]>rows=rows(csv);List<TargetPriceConsensusSnapshot>out=new ArrayList<>();for(String[]v:rows)out.add(saveTargetPrice(new TargetPriceConsensusCommand(v[0],date(v[1]),decimal(v[2]),decimal(v[3]),decimal(v[4]),nullableInt(v[5]),source(v[6]),nullable(v[7]))));metrics.recordConsensusImport("target_price","success");return out;}catch(RuntimeException e){metrics.recordConsensusImport("target_price","failure");throw new IllegalArgumentException("invalid target price consensus CSV",e);}}
 public List<EarningsConsensusSnapshot> findEarnings(String code,Integer year,Integer quarter){return limit(earnings.find(code,year,quarter));}public List<TargetPriceConsensusSnapshot> findTargetPrices(String code){return limit(targets.findByStockCode(code));}
 private ConsensusStatus status(LocalDate date){return date.isBefore(LocalDate.now(clock).minusDays(properties.getLookbackDays()))?ConsensusStatus.STALE:ConsensusStatus.ACTIVE;}
 private static BigDecimal upside(BigDecimal target,BigDecimal current){return current==null||current.signum()==0?null:target.subtract(current).multiply(BigDecimal.valueOf(100)).divide(current.abs(),4,RoundingMode.HALF_UP);}
 private <T> List<T> limit(List<T> values){return values.stream().limit(Math.max(1,properties.getMaxItemsPerStock())).toList();}
 private static List<String[]> rows(byte[]csv){String text=new String(csv,StandardCharsets.UTF_8).replace("\uFEFF","");List<String[]>out=new ArrayList<>();String[]lines=text.split("\\R");for(int i=1;i<lines.length;i++)if(!lines[i].isBlank())out.add(parse(lines[i]));return out;}
 private static String[] parse(String line){List<String>v=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<line.length();i++){char c=line.charAt(i);if(c=='\"'){if(q&&i+1<line.length()&&line.charAt(i+1)=='\"'){b.append('\"');i++;}else q=!q;}else if(c==','&&!q){v.add(b.toString().trim());b.setLength(0);}else b.append(c);}v.add(b.toString().trim());return v.toArray(String[]::new);}
 private static BigDecimal decimal(String v){return v==null||v.isBlank()?null:new BigDecimal(v);}private static int integer(String v){return Integer.parseInt(v);}private static Integer nullableInt(String v){return v==null||v.isBlank()?null:integer(v);}private static LocalDate date(String v){return LocalDate.parse(v);}private static ConsensusSource source(String v){return v==null||v.isBlank()?ConsensusSource.CSV:ConsensusSource.valueOf(v.toUpperCase(Locale.ROOT));}private static String nullable(String v){return v==null||v.isBlank()?null:v;}private static String clean(String v){return nullable(v);}
}
