package seokhoon.trade.domain.research;
public enum NewsCategory { EARNINGS, ORDER_CONTRACT, POLICY, SECTOR_THEME, CAPITAL_RAISE,
    CONVERTIBLE_BOND, MAJOR_SHAREHOLDER, MANAGEMENT, PRODUCT, REGULATORY,
    PRICE_TARGET, MACRO, RISK, ETC }
