package seokhoon.trade.adapter.web;
import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.MediaType;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import seokhoon.trade.application.port.in.ConsensusUseCase;import seokhoon.trade.domain.research.*;import java.io.IOException;import java.util.List;
@RestController @RequestMapping("/api/research/consensus") public class ConsensusController {
 private final ConsensusUseCase useCase;public ConsensusController(ConsensusUseCase useCase){this.useCase=useCase;}
 @PostMapping(value="/earnings/import-csv",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)List<EarningsConsensusSnapshot> importEarnings(@RequestPart("file")MultipartFile file)throws IOException{return useCase.importEarningsCsv(file.getBytes());}
 @PostMapping(value="/target-price/import-csv",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)List<TargetPriceConsensusSnapshot> importTarget(@RequestPart("file")MultipartFile file)throws IOException{return useCase.importTargetPriceCsv(file.getBytes());}
 @PostMapping("/earnings")EarningsConsensusSnapshot saveEarnings(@RequestBody ConsensusUseCase.EarningsConsensusCommand command){return useCase.saveEarnings(new ConsensusUseCase.EarningsConsensusCommand(command.stockCode(),command.fiscalYear(),command.fiscalQuarter(),command.consensusDate(),command.expectedRevenue(),command.expectedOperatingIncome(),command.expectedNetIncome(),command.expectedOperatingMargin(),command.analystCount(),ConsensusSource.MANUAL,command.providerName()));}
 @PostMapping("/target-price")TargetPriceConsensusSnapshot saveTarget(@RequestBody ConsensusUseCase.TargetPriceConsensusCommand command){return useCase.saveTargetPrice(new ConsensusUseCase.TargetPriceConsensusCommand(command.stockCode(),command.consensusDate(),command.targetPrice(),command.currentPrice(),command.upsideRate(),command.analystCount(),ConsensusSource.MANUAL,command.providerName()));}
 @GetMapping("/earnings")List<EarningsConsensusSnapshot> earnings(@RequestParam String stockCode,@RequestParam(required=false)Integer fiscalYear,@RequestParam(required=false)Integer fiscalQuarter){return useCase.findEarnings(stockCode,fiscalYear,fiscalQuarter);}
 @GetMapping("/target-price")List<TargetPriceConsensusSnapshot> targets(@RequestParam String stockCode){return useCase.findTargetPrices(stockCode);}
}
