package seokhoon.trade.domain.market;

public enum InvestorType {
    FOREIGN, INSTITUTION, INDIVIDUAL, FINANCIAL_INVESTMENT, INSURANCE,
    INVESTMENT_TRUST, BANK, PENSION_FUND, PRIVATE_EQUITY, OTHER_INSTITUTION, ETC
}
