package seokhoon.trade.domain.scheduler;

public enum SchedulerName {
    CLOSING_BET_PRE_SCAN_14,
    CLOSING_BET_FINAL_REVIEW_15,
    EARLY_MARKET_PRE_OPEN_830,
    EARLY_MARKET_OPENING_905,
    EARLY_MARKET_FOLLOW_UP_920,
    EARLY_MARKET_PERFORMANCE_CAPTURE_930,
    MARKET_CALENDAR_SYNC,
    LIVE_POSITION_EXIT_MONITOR,
    LIVE_ORDER_RECONCILIATION,
    KIS_TOKEN_REFRESH,
    SECTOR_DAILY_SNAPSHOT,
    MARKET_INDEX_IMPORT,
    INVESTOR_FLOW_IMPORT,
    SUPPLY_DEMAND_ANALYSIS,
    VALUATION_AUTO_SNAPSHOT,
    RESEARCH_MORNING_NOTE,
    PAPER_TRADING_DAILY_REPORT
}
